/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import data.storable.Storable;
import data.storable.user.UserImpl;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public class App {
    public static void main(String[] args) {
        BusinessLogic bl = new BusinessLogic(BigDecimal.valueOf(99999), BigDecimal.valueOf(99999));

        System.out.println(UUID.randomUUID());
        System.out.println(bl.user_add("123"));

        Map<UUID, Storable> map = new HashMap<>();
        Storable u1 = new UserImpl(UUID.randomUUID(), "1234");
        Storable u2 = new UserImpl(UUID.randomUUID(), "12345");
        map.put(u1.getID(), u1);
        map.put(u2.getID(), u2);

        System.out.println("ADD");

        for (Storable k : map.values()) {
            System.out.println(k + " " + k.getID());
        }

        System.out.println("REM-F");

        System.out.println(map.remove(u1.getID()));

        System.out.println("REM");

        for (Storable k : map.values()) {
            System.out.println(k + " " + k.getID());
        }

        System.out.println("REM-F");

        System.out.println(map.remove(UUID.randomUUID()));
    }
}
