/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.math.BigDecimal;
import java.util.UUID;

public class App {
    public static void main(String[] args) {
        BusinessLogic bl = new BusinessLogic(BigDecimal.valueOf(99999), BigDecimal.valueOf(99999));

        System.out.println(UUID.randomUUID());
        System.out.println(bl.user_add("123"));
    }
}
